version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/**
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: Europe/London
    groups:
      gha:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: Europe/London
    groups:
      npm:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directories:
      - /terraform/**
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: Europe/London
    groups:
      terraform:
        update-types:
          - minor
          - patch
