version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/**"
    schedule:
      interval: weekly
      day: monday
    groups:
      gha:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      npm:
        update-types:
          - minor
          - patch
